# Dockerfile.gulp
FROM node:18-alpine

# Crear directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y gulpfile.js
COPY package.json package-lock.json ./
COPY gulpfile.js ./

# Instalar dependencias
RUN npm install -g gulp-cli
RUN npm install

# Copiar el código fuente
COPY src ./src

# Comando por defecto
CMD ["gulp"]
